### ISSUE TITLE
 Notepad++ hangs and then unable to click on notepad++ window anywhere. #4295

### ISSUE THREAD

**Issue by pinodev** [p0358/notepadpp-CodeStats#10] opened 2019-05-03 23:46 UTC
Hi there,

Please see ticket https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4295, originally logged for Notepad++, but it turns out it is the time keeping plugins that mess with the application.

Is there a way to debug a plugin ?
(I mean, if I compile the plugin myself and I run Notepad++, and later see it freeze, would I be able to break in and debug to see where it's stuck ?)

Kind regards,

P.

**Comment by p0358** [comment] 2022-10-20 16:30
I'll close this one as it's duplicate of #4, where I commented now.

If it'd still happen, for debugging the best way is to enable debug logging in plugin settings just to see if issue can be spotted this way first.

Otherwise it gets trickier, you can clone the repo and open it in Visual Studio 2019 (not 2022...), then attach to process, but it will only work if the issue is in managed .NET code. If it's not, then you'd need debug symbols for particular Notepad++ version and attaching the debugger in native mode rather than managed to see where Notepad++ itself hangs if so happens...

**Closed as completed by p0358** 2022-10-20 16:30 UTC
